apiVersion: v1
kind: service
metadata:
  name: demo-service
  labels: 
    mylabelname: virtualization
spec:
  type: LoadBalancer
  - ports: 8000
    targetPort: 8000
  selector:
    name: pod
    app: demo
    