apiVersion: v1
kind: Service
metadata:
  name: demo-service

spec:
  type: LoadBalancer
  ports:
  - targetPort: 8000
    port: 80
    nodePort: 31111
  selector:
    app: virtualization
    type: back-end
    